name: genenv
channels:
  - alubbock
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cloudpickle=1.0.0
  - cycler=0.10.0
  - freetype=2.9.1
  - graphviz=2.38
  - icc_rt=2019.0.0
  - icu=58.2
  - intel-openmp=2019.1
  - joblib=0.13.2
  - jpeg=9b
  - kiwisolver=1.0.1
  - libiconv=1.15
  - libpng=1.6.36
  - libxml2=2.9.9
  - matplotlib=3.0.3
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - numpy=1.16.2
  - numpy-base=1.16.2
  - openssl=1.1.1b
  - pandas=0.24.2
  - patsy=0.5.1
  - pip=19.0.3
  - psutil=5.6.2
  - pydot=1.3.0
  - pygraphviz=1.5
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - python=3.7.2
  - python-dateutil=2.8.0
  - pytz=2018.9
  - qt=5.9.7
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - seaborn=0.9.0
  - setuptools=40.8.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.27.2
  - statsmodels=0.9.0
  - tornado=6.0.1
  - vc=14.1
  - vs2015_runtime=14.15.26706
  - wheel=0.33.1
  - wincertstore=0.2
  - zlib=1.2.11
  - pip:
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - babel==2.6.0
    - chardet==3.0.4
    - colorama==0.4.1
    - deap==1.2.2
    - debtcollector==1.21.0
    - decorator==4.4.0
    - fasteners==0.14.1
    - idna==2.8
    - ipython-genutils==0.2.0
    - iso8601==0.1.12
    - jsonschema==3.0.1
    - jupyter-core==4.4.0
    - liac-arff==2.4.0
    - mock==2.0.0
    - monotonic==1.5
    - more-itertools==7.0.0
    - nbformat==4.4.0
    - netaddr==0.7.19
    - netifaces==0.10.9
    - objgraph==3.4.0
    - openml==0.8.0
    - oslo-concurrency==3.29.1
    - oslo-config==6.8.1
    - oslo-i18n==3.23.1
    - oslo-utils==3.40.3
    - pbr==5.1.3
    - pluggy==0.9.0
    - py==1.8.0
    - pyrsistent==0.14.11
    - pytest==4.4.1
    - python-graphviz==0.10.1
    - pyyaml==5.1
    - requests==2.21.0
    - rfc3986==1.3.0
    - stevedore==1.30.1
    - stopit==1.1.2
    - traitlets==4.3.2
    - urllib3==1.24.2
    - wrapt==1.11.1
    - xmltodict==0.12.0


